import pandas as pd
import numpy as np
import time
import json
import os
from pathlib import Path

from pm.power import PowerMeter
from LabAuto.laser_remote import LaserController

def verify_pp_table(laser, pm, config_path, pp_df_path):
    # 1. Load the configuration to get the channel mapping
    with open(config_path, "r") as f:
        parameters = json.load(f)
        
    wavelength_arr = parameters["wavelength_arr"]
    channel_arr = parameters["channel_arr"]
    
    # 2. Load the PP table generated by the binary search
    pp_df = pd.read_csv(pp_df_path, index_col=0)
    
    # Extract the target power column names (which are strings like "10", "50", "100")
    target_powers = pp_df.columns 
    
    # Initialize an empty array to store the verified measurements
    verified_table = np.zeros((len(wavelength_arr), len(target_powers)))
    
    print("Zeroing Power Meter...")
    pm.zero_sensor()
    
    try:
        # 3. Iterate through every wavelength and target power
        for i, wavelength in enumerate(wavelength_arr):
            channel = str(channel_arr[i])
            
            print(f"\n--- Verifying Wavelength: {wavelength} nm (Channel {channel}) ---")
            pm.config_meter(wavelength, average_count=10)
            
            # Tell the laser to switch to this wavelength
            laser.send_cmd({"channel": channel, "wavelength": wavelength}, wait_for_reply=True)
            time.sleep(1)
            
            for j, target_power_str in enumerate(target_powers):
                # Grab the calculated PP from the dataframe
                pp = float(pp_df.loc[wavelength, target_power_str])
                
                # Send the specific PP to the laser and turn it on
                laser.send_cmd({"channel": channel, "power": pp, "on": 1}, wait_for_reply=True)
                time.sleep(1) # Give the AOTF a moment to stabilize
                
                # Measure the optical power
                _, p = pm.measure_power(measure_interval=0.2, num_points=10)
                measured_power_nw = np.mean(p[-3:]) * 1e9 # Convert Watts back to nanoWatts
                
                verified_table[i, j] = measured_power_nw
                
                print(f"Target: {target_power_str:>5} nW | Used PP: {pp:>6.2f}% | Actual: {measured_power_nw:>8.2f} nW")

                laser.send_cmd({"channel": channel, "on": 1}, wait_for_reply=True)
                time.sleep(1)
                

    finally:
        # 4. Format the final output DataFrame
        verified_df = pd.DataFrame(
            verified_table, 
            index=wavelength_arr, 
            columns=target_powers
        )
        
        verified_df.index.name = "Wavelength (nm)"
        verified_df.columns.name = "Target Power (nW)"
        
        return verified_df


if __name__ == "__main__":
    LIGHT_IP = "10.0.0.2" 
    
    config_path = Path("config") / "power_config.json"
    pp_df_path = Path("calibration") / "pp_df.csv"
    output_path = Path("calibration") / "verified_power_df.csv"
    
    print("Connecting to Laser PC...")
    laser = LaserController(LIGHT_IP, 5001)
    print("Laser connected.")
    
    pm = PowerMeter()
    
    try:
        # Run the verification routine
        verified_df = verify_pp_table(laser, pm, config_path, pp_df_path)
        
        # Save the results
        os.makedirs("calibration", exist_ok=True)
        verified_df.to_csv(output_path, index=True)
        print(f"\nVerification complete. Results saved to {output_path}")
        
    except Exception as e:
        print(f"Error during verification: {e}")
        
    finally:
        pm.close_meter()
        laser.close()
        print("Hardware disconnected safely.")